### ISSUE TITLE
replace_roman_numerals issue

### ISSUE THREAD

**Issue by adamtootle** [seven1m/bible_ref#3]
`replace_roman_numerals` in BibleRef::Book turns "Isaiah" into "1saiah" which gets parsed as "1 Samuel"

I've thought about requiring a space after the Roman numerals, so that `/^i/i` becomes `/^i /i` but wanted to ask about it first. I don't use Roman numerals at all so it's not a huge issue for me but I wasn't sure if that may cause problems.

**Comment by seven1m** [comment]
Yeah let's require a space after the roman numeral. :+1:

**Comment by seven1m** [comment]
Gosh I forgot about this issue. Fixed in bff3dab96d8dd37b82b8171776c29f5cb9435812.
